---
layout:     post
title:      Flutter异步探究
subtitle:   Flutter异步探究
date:       2023-05-06
author:     LXY
header-img: img/home1.jpeg
catalog: true
tags:
    - flutter
---
之前看网上很多文章说，Dart没有多线程！！那么Dart是如何实现异步操作的呢?今天就让我们一探究竟~
# 一、事件循环

在Dart的线程中也存在事件循环和消息队列的概念，但在Dart中线程叫做isolate。应用程序启动后，开始执行main函数并运行main isolate。

每个isolate包含一个事件循环以及两个事件队列，event loop事件循环，以及event queue和microtask queue事件队列，event和microtask队列有点类似iOS的source0和source1。

- 事件队列（event queue）：包括所有的外来事件，I/O、mouse events、drawing events、timers、isolate之间的信息传递。

- 微任务队列（microtask queue）：表示一个短时间内就会完成的异步任务。它的优先级最高，高于event queue，只要队列中还有任务，就可以一直霸占着事件循环。microtask queue添加的任务主要是由Dart内部产生。

怎么理解这个呢？我们可以借鉴下面这张图看看Dart的事件循环所谓的优先级是怎样的一个过程。
![](https://images.xiaozhuanlan.com/photo/2022/09c210b45d31c856d73276fea3d5e024.png)



上图可见，当isolate开始执行后，会先处理microtask的事件，当microtask队列中没有事件后，才会处理event队列中的事件，并按照这个顺序反复执行。但需要注意的是，当执行microtask事件时，会阻塞event队列的事件执行，这样就会导致渲染、手势响应等event事件响应延时。为了保证渲染和手势响应，应该尽量将耗时操作放在event队列中。

在我们日常开发用的多的还是优先级低的事件队列，Dart为 event queue的任务建立提供了一层封装，就是我们在Dart中经常用到的**Future**。

正常情况下，一个 Future 异步任务的执行是相对简单的：

声明一个 Future 时，Dart 会将异步任务的函数执行体放入event queue，然后立即返回，后续的代码继续同步执行。

当同步执行的代码执行完毕后，event queue会按照加入event queue的顺序（即声明顺序），依次取出事件，最后同步执行 Future 的函数体及后续的操作。

# 二、Future 、async和await

首先我们可以引入一个简单的例子，来看看这个Future的基本使用:
```
  void _testAction() {

    print('====任务开始');
    Future(() {
      //耗时操作
      print('====耗时任务结束');
    });
    print('====任务结束');
  }
```
打印结果如下：
```
I/flutter ( 9335): ====任务开始
I/flutter ( 9335): ====任务结束
I/flutter ( 9335): ====耗时任务结束
```
看起来是不是很像iOS和安卓的异步操作？

**可以看出，在当前线程中，Future 所包含的任务是异步执行的，先进行Future之后的任务，再执行Future内的函数，如果我们想要同步执行的话，也就是先执行Future 内的函数再执行之后的事件，可用通过关键字async和await:**

```
Future _testAction() async{

    print('====任务开始');
    await Future(() {
      //耗时操作
      print('====耗时任务结束');
    });
    print('====任务结束');
  }
```

打印结果如下：
```
I/flutter ( 9335): ====任务开始
I/flutter ( 9335): ====耗时任务结束
I/flutter ( 9335): ====任务结束
```

**可以看出，加上关键字async和await后，Future后面的代码就要等到Future执行完成之后再执行，但是整个函数变成了一个异步函数，那么整体的函数会不会阻碍后面的函数执行呢？**

```
void _clickAction(){
    _testAction();
    print('_testAction之后写的代码');
  }
```
打印结果如下：
```
I/flutter (11676): ====任务开始
I/flutter (11676): _testAction之后写的代码
I/flutter (11676): ====耗时任务结束
I/flutter (11676): ====任务结束
```
加入**async、await关键字**
```
  void _clickAction() async{
    await _testAction();
    print('_testAction之后写的代码');
  }
```
打印结果如下：
```
I/flutter (11676): ====任务开始
I/flutter (11676): ====耗时任务结束
I/flutter (11676): ====任务结束
I/flutter (11676): _testAction之后写的代码
```
**查看两个打印结果：**
一个是_testAction执行完之后，当遇到await阻塞后先执行_testAction之后的代码```print('_testAction之后写的代码')```，当_testAction之后的代码执行完成后，在去执行await异步的代码```print('====耗时任务结束');```
另一个则是**_testAction方法中的代码都执行完成**，再去执行_testAction之后的代码。

两者的区别就是一个_clickAction是同步函数，一个_clickAction则是异步函数，用到 **async** 关键字；在添加async函数之后，_clickAction这整个函数已经是个异步函数，_clickAction会返回一个Future对象。


**异步函数即在函数头中包含关键字async的函数。**

- async: 用来表示函数是异步的，定义的函数会返回一个Future对象。
- await：后面跟着一个Future，表示等待该异步任务完成，异步任务完成后才会继续往下执行。await只能出现在异步函数内部(await单独存在是没有意义的，要配合async使用)。能够让我们可以像写同步代码那样来执行异步任务而不使用回调的方式。

# 三、Future.then()
**一"码"当先**
```
void _clickAction() async{
    await _testAction();
    print('_testAction之后写的代码');
  }

   Future _testAction() async{

    print('====任务开始');
    Future future = Future(() {
      //耗时操作
      print('====耗时任务进行中');
    });
    future.then((value){
      print('====耗时任务结束');
    });
    print('====任务结束');
  }
```
**输出结果:**
```
I/flutter (32218): ====任务开始
I/flutter (32218): ====任务结束
I/flutter (32218): _testAction之后写的代码
I/flutter (32218): ====耗时任务进行中
I/flutter (32218): ====耗时任务结束
```
可以看到，Future then是在Future的异步函数执行完成之后，去运行then里面的代码

因为Future 返回的是一个Future对象，获取这个对象，调用then方法，我们发现then里面的任务是在Future任务块结束后执行的。
不妨再多加两个then方法的调用：
```
  void _clickAction() async{
    await _testAction();
    print('_testAction之后写的代码');
  }

   Future _testAction() async{

    print('====任务开始');
    Future future = Future(() {
      //耗时操作
      print('====耗时任务进行中');
    });
    future.then((value){
      print('====耗时任务结束1');
    });
    future.then((value){
      print('====耗时任务结束2');
    });
    future.then((value){
      print('====耗时任务结束3');
    });
    print('====任务结束');
  }
```
```
I/flutter (32218): ====任务开始
I/flutter (32218): ====任务结束
I/flutter (32218): _testAction之后写的代码
I/flutter (32218): ====耗时任务进行中
I/flutter (32218): ====耗时任务结束1
I/flutter (32218): ====耗时任务结束2
I/flutter (32218): ====耗时任务结束3
```
由此可知，then方法是用来注册一个Future完成时要调用的回调。如果 Future 有多个then，它们也会按照链接的先后顺序同步执行，同时也会共用一个event loop。
查看then方法源码可知then方法最终返回也是一个Future对象：
```
Future<R> then<R>(FutureOr<R> onValue(T value), {Function? onError});
```

**综合示例分析：**
```
void testFuture() {
    Future x1 = Future(() => null);
    Future x2 = x1.then((value) {
      print('6');
      scheduleMicrotask(() => print('7'));
    });
    x2.then((value) => print('8'));

    Future x = Future(() => print('1'));
    x.then((value) {
      print('4');
      Future(() => print('9'));
    }).then((value) => print('10'));

    Future(() => print('2'));

    scheduleMicrotask(() => print('3'));

    print('5');
  }
```
输出结果：
```
I/flutter (32218): 5
I/flutter (32218): 3
I/flutter (32218): 6
I/flutter (32218): 8
I/flutter (32218): 7
I/flutter (32218): 1
I/flutter (32218): 4
I/flutter (32218): 10
I/flutter (32218): 2
I/flutter (32218): 9
```
分析:

- 首先调用testFuture()函数，所以优先打印 5。
- 执行优先级较高的microtask事件3。
- 然后按照Future的声明顺序执行，x1 的then时间打印6。此时只是将7这个microtask任务添加到队列中，暂时还没轮到打印7执行。
- 打印完6后，继续立即执行x2.then方法，所以打印8。
- 打印完8之后，此时队列里有添加进来的优先级高的7，所以打印7。
- 然后继续向下执行，打印1，接着4，接着就是10。同样，此处的9只是添加进event queue，并不执行。
- 对于2和9的打印顺序，要看加入到event queue的时间，要知道任务2是在一开始打印5之前就添加进了event queue， 所以2应该在9之前，10之后打印。9才是最后被添加进事件队列的，所以最后打印。

结论：

- then() 函数是前面Future函数体执行结束后立即执行的，可以看作是一个微任务，优先级高。
- 微任务队列（microtask queue）优先级高于事件队列（event queue）。

# 四、Future.catchError()
顾名思义，catchError()是用来捕捉Future抛出的错误的。
**一"码"当先**

先then再链式调catchError
```
 Future _testAction() async{

    print('====任务开始');
    Future future = Future(() {
      //耗时操作
      throw '耗时操作异常';
    });
    future
        .then((value) => print('结束data=$value'))
        .catchError((e) => print('捕获到了：' + e.toString()));
    print('====任务结束');
  }
```
输出：
```
I/flutter ( 3327): ====任务开始
I/flutter ( 3327): ====任务结束
I/flutter ( 3327): 捕获到了：耗时操作异常
```
先catchError再链式调then
```
 Future _testAction() async{

    print('====任务开始');
    Future future = Future(() {
      //耗时操作
      throw '耗时操作异常';
    });
    future
        .catchError((e) => print('捕获到了：' + e.toString()))
        .then((value) => print('结束data=$value'));
    print('====任务结束');
  }
```
输出：
```
I/flutter ( 3327): ====任务开始
I/flutter ( 3327): ====任务结束
I/flutter ( 3327): 捕获到了：耗时操作异常
I/flutter ( 3327): 结束data=null
```
先then再链式调catchError，最终捕获到了原始Future 所抛出的错误，而我们可以看到此时then()函数暂未打印，说明一旦原Future跑出错误，then()不会执行。

先catchError再链式调then，可以看到，then也打印出来，此时的then已经不是future的then,而是catchError返回future的then



Future.catchError回调只处理原始Future抛出的错误，不能处理回调函数抛出的错误，onError只能处理当前Future的错误：

先then再链式调catchError
```
   Future _testAction() async{

    print('====任务开始');
    Future future = Future(() {
      //耗时操作
      throw '耗时操作异常';
    });
    future
        .then((value) => print('结束data=$value'), onError: (e) => print('then出错误了'))
        .catchError((e) => print('捕获到了：' + e.toString()));

    print('====任务结束');
  }
```
输出
```
I/flutter ( 3327): ====任务开始
I/flutter ( 3327): ====任务结束
I/flutter ( 3327): then出错误了
```
先catchError再链式调then
```
   Future _testAction() async{

    print('====任务开始');
    Future future = Future(() {
      //耗时操作
      throw '耗时操作异常';
    });
    future
        .catchError((e) => print('捕获到了：' + e.toString()))
        .then((value) => print('结束data=$value'), onError: (e) => print('then出错误了'));

    print('====任务结束');
  }
```
输出
```
I/flutter ( 3327): ====任务开始
I/flutter ( 3327): ====任务结束
I/flutter ( 3327): 捕获到了：耗时操作异常
I/flutter ( 3327): 结束data=null
```
catchError源码：
```
Future<T> catchError(Function onError, {bool test(Object error)?});
```
上面两个例子可以看出:

- 先catchError再链式调then时，catchError()捕获原Future抛出错误时，then()里的onError就不执行了，因为catchError源码可知，catchError()返回的也是一个Future ,且返回的Future无错误抛出，所以当调用then函数时，里面的onError就无错误可处理，不打印。

- 先then再链式调catchError时，此时onError捕获到了原Future抛出的错误，并处理打印。然后返回的Future 无错误抛出，所以最后的catchError无错误处理，不打印。

# 五、Future.whenComplete()
Future.whenComplete()在Future 完成之后总是会调用，**不管是抛出错误还是正常执行结束**。
**在Future链式调用中，只要前面的Future完成，whenComplete就会执行！！**

```
   Future _testAction() async{

    print('====任务开始');
    Future future = Future(() {
      //耗时操作
      print('====耗时操作异常');
    });
    
    future
        .whenComplete(() => print('future完成了'))
        .then((value) => print('结束data=$value'), onError: (e) => print('then出错误了'));

    print('====任务结束');
  }
```
```
I/flutter ( 3327): ====任务开始
I/flutter ( 3327): ====任务结束
I/flutter ( 3327): ====耗时操作异常
I/flutter ( 3327): future完成了
I/flutter ( 3327): 结束data=null
```
# 六、Future.wait()

Future.wait() 等同于**多个线程任务处理结束之后统一处理任务的时机获取**，例如多个网络请求结束之后，统一刷新UI，类似于iOS 中GCD的Dispatch Group

示例代码如下：
```
   Future _testAction() async{

     Future.wait([
       Future(() {
         print('1 执行');
         return '任务1 ';
       }),
       Future(() {
         print('2 执行');
         return '任务2 ';
       }),
       Future(() {
         print('3 执行');
         return '任务3 ';
       })
     ]).then((value) => print(value[0] + value[1] + value[2] +"执行完成之后统一处理"));
  }
```
输出结果：
```
I/flutter ( 3327): 1 执行
I/flutter ( 3327): 2 执行
I/flutter ( 3327): 3 执行
I/flutter ( 3327): 任务1 任务2 任务3 执行完成之后统一处理
```
简单理解就是，wait()中的Future执行体依次先执行，然后最后再通过then去处理所有的Future返回的结果。

# 七、Dart多线程Isolate
Isolate是一个非常底层的api，我们可以通过Isolate.spawn()方法进行调用。

先做一个简单的实验，对比一下:
模拟一个耗时操作，代码如下：
```
 static void isoFunc0(String message) {
    // 模拟耗时操作
    sleep(Duration(seconds: 2));

    print("message is $message");
  }
```
执行代码如下：
```
    print('1');
    isoFunc0('111');
    print('2');

```
输出结果:
```
I/flutter ( 3327): 1
I/flutter ( 3327): message is 111
I/flutter ( 3327): 2
```
会发现isoFunc0会阻塞主线程，``print('2');``要等到``isoFunc0('111');``执行完成之后再去执行。


利用Future异步执行耗时操作：
```
    print('1');
    Future((){
      isoFunc0('111');
    });
    print('2');
```
输出结果:
```
I/flutter ( 3327): 1
I/flutter ( 3327): 2
I/flutter ( 3327): message is 111
```
会发现isoFunc0不会会阻塞主线程，``print('2');``不用等到``isoFunc0('111');``执行完成之后再去执行。

使用Isolate，代码如下：
```
    print("外部代码 1");
    Isolate.spawn(isoFunc0,'111');
    print("外部代码 2");
```
输出结果:
```
I/flutter ( 3327): 外部代码 1
I/flutter ( 3327): 外部代码 2
I/flutter ( 3327): message is 111
```
##1、Isolate与异步操作的区别
我们知道异步操作并没有开辟一条子线程，而是在线程空闲时去执行异步操作。而Isolate不同，我们可以通过下面代码看到区别。

```
    print("外部代码 1");
    Isolate.spawn(isoFunc0,'111');
    sleep(Duration(seconds: 3));
    print("外部代码 2");
```

执行结果为：
```
I/flutter ( 3327): 外部代码 1
I/flutter ( 3327): message is 111
I/flutter ( 3327): 外部代码 2
```
可以看到，尽管主线程中有任务执行没有空闲，但是Isolate.spawn的操作仍然执行了，这是异步操作所不具备的。

## 2、Isolate不是严格意义上的多线程
实际上，Isolate更像是进程而不是线程，因为他拥有独立的内存空间，并且他与子线程之间的通信需要借助到端口（Port）概念的api，这些特性让它看起来更像是进程。
我们通过代码验证一下：
```
  static String _st = "222";

  static void isoFunc0(String message) {
    _st = message;
    print("message is $message");
  }
```
```
print("外部代码 1");
Isolate.spawn(isoFunc0,'111');
sleep(Duration(seconds: 3));
print("data is $_st");
print("外部代码 2");
```
输出结果：
```
I/flutter ( 3327): 外部代码 1
I/flutter ( 3327): message is 111
I/flutter ( 3327): data is 222
I/flutter ( 3327): 外部代码 2
```
可以看到，尽管Isolate中修改了_data的值，但是外部的_data的值并没有随之改变，显然，这个结果明显不符合多线程的特性。

## 3、ReceivePort
如果我们需要将Isolate的结果返回，我们需要使用端口ReceivePort来进行传递。我们将ReceivePort作为参数传递给Isolate，Isolate执行完成后通过Port的send方法将结果传递出来，外部通过listen得到结果。

```
  static void isoFunc(SendPort port) {
    sleep(Duration(seconds: 2));
    port.send("发送消息");
  }

  void isolateTest() async {
    print("外部代码 1");
    ReceivePort port = ReceivePort();
    Isolate iso = await Isolate.spawn(isoFunc, port.sendPort);
    port.listen((message) {
      print("接收回调 $message");
      port.close();
      iso.kill();
    });
    print("外部代码 2");
  }
```
执行结果为：
```
I/flutter ( 3327): 外部代码 1
I/flutter ( 3327): 外部代码 2
I/flutter ( 3327): 接收回调 发送消息
```
**port.listen到结果后，我们要将端口关闭，杀死Isolate。**


#八、Dart多线程compute
除了Isolate，Dart还给我们提供compute接口。

查看compute定义：
```
const _ComputeImpl compute = _isolates.compute;
```
查看点进去compute后可以查看
```
Future<R> compute<Q, R>(isolates.ComputeCallback<Q, R> callback, Q message, { String? debugLabel }) async
```
会发现compute实际上是对Isolate封装，使用起来也更加简单
```
  static String funcC(int count) {
    return '回调参数$count';
  }
  void computeDemo() {
    print('1');
    compute(funcC, 10).then((value) => print(value));
    sleep(Duration(seconds: 2));
    print('2');
  }
```
输出：
```
I/flutter ( 3327): 1
I/flutter ( 3327): 2
I/flutter ( 3327): 回调参数10
```
有结果可见，和Isolate的现象是一样的。

# 九、compute与Future异步结合多线程使用
```
 static funcC(int count) => print('funcC:$count');
 void computeDemo() {
    Future(() => compute(funcC, 1)).then((value) => print('1结束'));
    Future(() => compute(funcC, 2)).then((value) => print('2结束'));
    Future(() => compute(funcC, 3)).then((value) => print('3结束'));
    Future(() => compute(funcC, 4)).then((value) => print('4结束'));
    Future(() => compute(funcC, 5)).then((value) => print('5结束'));
 }
```
输出：
```
I/flutter ( 3327): funcC:3
I/flutter ( 3327): funcC:1
I/flutter ( 3327): 3结束
I/flutter ( 3327): 1结束
I/flutter ( 3327): funcC:2
I/flutter ( 3327): 2结束
I/flutter ( 3327): funcC:4
I/flutter ( 3327): 4结束
I/flutter ( 3327): funcC:5
I/flutter ( 3327): 5结束
```
此时的异步任务中开启了子线程，=> 符号的意思是返回，所以then()的调用也是在子线程中进行。

将代码改成：
```
  static funcC(int count) => print('funcC:$count');
  void computeDemo() {
    Future(() {
      compute(funcC, 1);
    }).then((value) => print('1结束'));
    Future(() {
      compute(funcC, 2);
    }).then((value) => print('2结束'));
    Future(() {
      compute(funcC, 3);
    }).then((value) => print('3结束'));
    Future(() {
      compute(funcC, 4);
    }).then((value) => print('4结束'));
    Future(() {
      compute(funcC, 5);
    }).then((value) => print('5结束'));
  }
```
输出结果：
```
I/flutter ( 3327): 1结束
I/flutter ( 3327): 2结束
I/flutter ( 3327): 3结束
I/flutter ( 3327): 4结束
I/flutter ( 3327): 5结束
I/flutter ( 3327): funcC:3
I/flutter ( 3327): funcC:1
I/flutter ( 3327): funcC:2
I/flutter ( 3327): funcC:4
I/flutter ( 3327): funcC:5
```
可以发现，then的执行顺序是按照调用顺序的，原因是因为此时的then的调用者是Future本身，此处没有=>符号里的返回的意思，所以此时按声明顺序打印。

如果将Future中的compute前面加上return，代码如下：
```
  static funcC(int count) => print('funcC:$count');
  void computeDemo() {
    Future(() {
      return compute(funcC, 1);
    }).then((value) => print('1结束'));
    Future(() {
      return compute(funcC, 2);
    }).then((value) => print('2结束'));
    Future(() {
      return compute(funcC, 3);
    }).then((value) => print('3结束'));
    Future(() {
      return compute(funcC, 4);
    }).then((value) => print('4结束'));
    Future(() {
      return compute(funcC, 5);
    }).then((value) => print('5结束'));
  }
```

输出结果：
```
I/flutter ( 3327): funcC:4
I/flutter ( 3327): funcC:3
I/flutter ( 3327): funcC:1
I/flutter ( 3327): 4结束
I/flutter ( 3327): 3结束
I/flutter ( 3327): 1结束
I/flutter ( 3327): funcC:2
I/flutter ( 3327): 2结束
I/flutter ( 3327): funcC:5
I/flutter ( 3327): 5结束
```

可以发现输出结果又变成无序的了